name: Make ABB and Push into release tab

on:
  push:
    branches:
      - '*'  # Trigger on pushes to all branches
  pull_request:
    branches:
      - '*'  # Trigger on pushes to all branches
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  build:
    runs-on: macos-latest
    permissions: write-all

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: "Setup Dart and Flutter"
      uses: subosito/flutter-action@v2 
      with:
        channel: 'master'
        

    - name: Install dependencies
      run: flutter pub get
    # Add this new step to accept Android licenses
    - name: Accept Android SDK licenses
      run: |
        yes | flutter doctor --android-licenses
    # - name: Run Flutter Launcher Icons
    #   # This step runs the flutter_launcher_icons package to generate app icons
    #   run: flutter pub run flutter_launcher_icons
    # - name: "Splash Screen"
    #   # This step runs the flutter_native_splash package to generate a splash screen
    #   run: dart run flutter_native_splash:create
  
      
# dart run build_runner build --delete-conflicting-outputs
    - name: "Build Flutter ABB Project"
      run: |
        flutter build appbundle --release

    - name: Push into Releases Tab
      uses: ncipollo/release-action@v1
      with:
        artifacts: "build/app/outputs/bundle/release/*"
        tag: v1.0.${{ github.run_number }}
        token: ${{ secrets.GITHUB_TOKEN}}