name: Make APK and Push into release tab

on:
  push:
    branches:
      - '*'  # Trigger on pushes to all branches
  pull_request:
    branches:
      - '*'  # Trigger on pushes to all branches
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  build:
    runs-on: macos-latest
    permissions: write-all

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: "Setup Dart and Flutter"
      uses: subosito/flutter-action@v2 
      with:
        channel: 'master'
        

    - name: Install dependencies
      run: flutter pub get
    # Add this new step to accept Android licenses
    - name: Accept Android SDK licenses
      run: |
        yes | sdkmanager --licenses
      
# dart run build_runner build --delete-conflicting-outputs
    - name: "Build Flutter APK Project"
      run: |
        flutter build  apk   --release

    - name: Push into Releases Tab
      uses: ncipollo/release-action@v1
      with:
        artifacts: "build/app/outputs/flutter-apk/*"
        tag: v1.0.${{ github.run_number }}
        token: ${{ secrets.GITHUB_TOKEN}}